### ISSUE TITLE
[Feature] Rawdevice

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#9]
Sometimes, we're interested only in performance of the layer being currently researched, so file system isn’t needed while testing.

Slight increase in code complexity, but otherwise pretty straightforward, when randomly choosing a file to work with, we always return the specified device. We also need to be careful not to write/read beyond the device's size.

**Comment by bengland2** [comment]
any chance we could cache the "file" object or equivalent for the block device somewhere in the fsop "self" object, so the open/close doesn't happen every time?  open/close impacts buffer cache  behavior, I think.   Also this may impact performance if you are using a really fast block device.    Of course, if you combine this with O_DIRECT then the cache doesn't come into play.   

Maybe we need a separate fsop class for block devices?   Would that be easier?  so instead of class FSOPCtxt you would have class BlkDevContext and FSContext or something like that?      This way there would be less conditional logic to maintain, which is the whole idea of object-oriented programming.

**Comment by spetrovi** [comment]
Hmm, not sure if I want to create clone of FSOPCtxt, since for the block device, the class would be 99.9% the same.
I think the conditionals would be pretty justified in this case. I'll try to look into some tricks that could allow us to keep the block device open the whole time.

**Comment by bengland2** [comment]
no big deal, do it your way, just thought I'd ask in case it was easier.

**Comment by spetrovi** [comment]
Another problem I remembered was storing the IO pointer in case we want to do sequential read/write. 
If we open/close the file every time, we would need to lseek current offset every time after open.
If we store the file descriptor somewhere and keep the file open, the pointer will be always where the previous IO left off! I think this is the way.

**Comment by spetrovi** [comment]
I found a pretty good solution.
I open the device and store the file descriptor in FSOPCtx constructor,
This is then used through self.rawdevice_fd in all the operations.
File is closed after the test ends via worker_thread end_test method
There is still some testing to be done, but looks promising (branch feature-rawdevice)

**Comment by bengland2** [comment]
+1
